name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, vehicules-service, trafic-service, incidents-service, notifications-service, gateway]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
        working-directory: ./services/${{ matrix.service }}
      - run: node --check server.js
        working-directory: ./services/${{ matrix.service }}